services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_projecttracker
    restart: always
    environment:
      POSTGRES_DB: projecttracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d projecttracker"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: aptavis-backend/Dockerfile
    container_name: backend_aptavis
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: aptavis-frontend/Dockerfile
    container_name: frontend_aptavis
    restart: always
    ports:
      - "8081:8080"
    environment:
      - BACKEND_API_URL=http://backend:8080/aptavis-backend/rest
    depends_on:
      - backend

volumes:
  postgres_data:
